name: Run Python Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install airtest
      - name: Prepare android emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
      - name: Run tests with pytest
        run: python -m airtest run "invalidLogin.air" --device Android:///